name: orbit_cola
channels:
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - requests
  - glob
  - os
  - pip:
      - astropy
      - dash
      - dash_bootstrap_components
      - mysql-connector-python
      - sgp4
      - sshtunnel
      - configsparser
